version: '3.9'
services:
  typesu:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/opt/typesu"
      - "/opt/typesu/node_modules"
    environment:
      - NEXT_WEBPACK_USEPOLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

      